version: '3.4'

services:
  postgresql_database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=SafeAppDatabase
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      #- database-data:/var/lib/postgresql/data/

  saveapi:
    image: saveapi
    build:
      context: .
      dockerfile: SafeApp/Dockerfile
    ports:
      - "8382:80"
      - "8383:443"
    environment:
      ASPNETCORE_URLS: "https://+:443;http://+:80"
      ASPNETCORE_HTTPS_PORT: "8383"
      ASPNETCORE_ENVIRONMENT: "Development"
    depends_on:
      - postgresql_database
    volumes:
      - ${APPDATA}\Microsoft\UserSecrets\:/root/.microsoft/usersecrets
      - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/

  saveclientapp:
    image: saveclientapp
    build:
      dockerfile: ClientApp/Dockerfile
    ports:
      - "4569:4569"
    environment:
      VIRTUAL_HOST: "safeapp.com"
    volumes:
      - "angular:/usr/src/app"
    depends_on:
      - saveapi

volumes:
    #database-data:
    pgadmin:
    angular: