version: '3.4'

services:
  postgresql_database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=SafeAppDatabase
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      #- database-data:/var/lib/postgresql/data/

  saveapi:
    image: saveapi
    build:
      context: .
      dockerfile: SafeApp/Dockerfile
    ports:
      - "8383:80"
    depends_on:
      - postgresql_database

  saveclientapp:
    image: saveclientapp
    build:
      dockerfile: ClientApp/Dockerfile
    ports:
      - "4569:80"
    volumes:
      - "angular:/usr/src/app"
    depends_on:
      - saveapi

volumes:
    #database-data:
    pgadmin:
    angular: